### ISSUE TITLE
R Modules

### ISSUE THREAD

**Issue by DanRunfola** [itpir/aiddata-sciclone#4]
The following R libraries would be helpful to have installed:
RandomFields
sp
spdep
psych
FNN

rgl
(Dependency: apt-get install libX11-dev freeglut3 freeglut3-dev)

ggplot2

raster
GISTools
stringr
R.utils
MatchIt
RLeaflet

**Comment by sgoodm** [comment]
- RandomFields - installed
- sp - installed
- spdep - installed
- psych - installed
- FNN - installed
-rgl - **NOT** installed
- ggplot2 - installed
- raster - installed (see (#1)[1])
- GISTools - **error** during installation
- stringr - installed
- R.utils -installed
- MatchIt - installed
- RLeaflet - **NOT** installed (not available for R 3.1.0)
